version: '3.1'

name: Dockerrrr

services:
  mongo:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017

  backend:
    build: 
      context: .
      dockerfile: Server/Dockerfile
    container_name: node-backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:3000"
    depends_on:
      - backend
